--Comprobar si es numerico
CREATE OR REPLACE FUNCTION isnumeric(text) RETURNS BOOLEAN AS $$
DECLARE x NUMERIC;
BEGIN
    x = $1::NUMERIC;
    RETURN TRUE;
EXCEPTION WHEN others THEN
    RAISE EXCEPTION 'LA FECHA NO PUEDE SER CARACTER';
END;
$$
STRICT
LANGUAGE plpgsql;
