CREATE OR REPLACE FUNCTION checkDate(character varying) RETURNS boolean AS $$
DECLARE
x DATE;
BEGIN
    x = $1::DATE;
    RETURN TRUE;
EXCEPTION
WHEN SQLSTATE '22008' THEN
    RAISE EXCEPTION 'LA FECHA INTRODUCIDA NO ES CORRECTA';
END;
$$ LANGUAGE plpgsql;
